spring:
  application:
    name: contact-service
server:
  port: 9001
#eureka:
 # client:
 #   serviceUrl:
 #     defaultZone: http://localhost:8671/eureka
  #instance:
   # preferIpAddress: true